### ISSUE TITLE
Iterating an out-of-bounds typed array should act as if the buffer is detached

### ISSUE THREAD

**Issue by ptomato** [tc39/proposal-resizablearraybuffer#100]
It's my understanding of the intention of this proposal is that when a typed array is out-of-bounds on its underlying buffer, it's treated as if the buffer is detached. In most APIs this is the case, but not in places that use [CreateArrayIterator](https://tc39.es/ecma262/#sec-createarrayiterator), i.e. `entries()`, `values()`, `keys()`, and iteration.

For example:
```js
const rab = new ArrayBuffer(4, { maxByteLength: 8 });
const fixedLength = new Uint8Array(rab, 0, 4);
const entries = fixedLength.values();
rab.resize(3);
console.log(entries.next().value);
```

After the `resize()` call, `rab`'s [[ArrayBufferData]] slot contains a data block of length 3, filled with 0's. Then in the abstract closure from CreateArrayIterator, we check in step 1.b.i.1 if the buffer is detached; it isn't, because the [[ArrayBufferData]] slot isn't null. Then we go on to the Get in step 1.b.v.2 which simply returns `undefined` because [IsValidIntegerIndex](https://tc39.es/proposal-resizablearraybuffer/#sec-isvalidintegerindex) returns out-of-bounds and therefore [IntegerIndexedElementGet](https://tc39.es/ecma262/#sec-integerindexedelementget) returns `undefined`.

I'd expect the code snippet above to log `undefined` according to the spec text, but it seems like the intention of the proposal is to throw a TypeError because the buffer should appear detached.

I'd recommend maybe replacing the IsDetachedBuffer in step 1.b.i.1 with [IsIntegerIndexedObjectOutOfBounds](https://tc39.es/proposal-resizablearraybuffer/#sec-isintegerindexedobjectoutofbounds) which also checks IsDetachedBuffer anyway.

**Comment by ljharb** [comment]
The proposal has reached stage 4; further questions should likely go to the [discourse](https://es.discourse.group).
