### ISSUE TITLE
DataView is not checking non-auto resizable ArrayBuffer's length

### ISSUE THREAD

**Issue by Constellation** [tc39/proposal-resizablearraybuffer#106]
Since https://tc39.es/proposal-resizablearraybuffer/#sec-getviewbytelength is always returning the specified length if the length is not auto, `IsViewOutOfBounds` passes without consulting to the underlying ArrayBuffer.

> 2. If view.[[ByteLength]] is not auto, then return view.[[ByteLength]].

So, I think the following code crashes, is it correct?

```js
var buffer = new ArrayBuffer(1024, { maxByteLength: 2048 });
// not auto, 16 byteLength DataView
var view = new DataView(buffer, 0, 16);
buffer.resize(0);
// Now, underlying buffer's byteLength becomes 0, but IsViewOutOfBounds passes.
view.setUint16(0, 32);
```

**Comment by syg** [comment]
Thanks for pointing this out, this is a bug in the DataView sections. The DataView stuff is kind of rough, sorry about that.
