### ISSUE TITLE
Maybe missing: modifications to ArrayBuffer.prototype.byteLength and SharedArrayBuffer.prototype.byteLength

### ISSUE THREAD

**Issue by marjakh** [tc39/proposal-resizablearraybuffer#15]
Don't ArrayBuffer.prototype.byteLength and SharedArrayBuffer.prototype.byteLength need to be modified to throw if they're called with a receiver which is a ResizableArrayBuffer / GrowableSharedArrayBuffer?

**Comment by syg** [comment]
Good catch, that seems right to me. Will write a PR.
