### ISSUE TITLE
GrowableSharedArrayBuffer.prototype.grow shouldn't throw if newLength == O.[[ArrayBufferByteLength]].

### ISSUE THREAD

**Issue by marjakh** [tc39/proposal-resizablearraybuffer#21]
Current:

If _newByteLength_ &le; ArrayBufferByteLength(_O_) or _newByteLength_ &gt; _O_.[[ArrayBufferMaxByteLength]], throw a *RangeError* exception.

IMO should be:

If _newByteLength_ &lt; ArrayBufferByteLength(_O_) or _newByteLength_ &gt; _O_.[[ArrayBufferMaxByteLength]], throw a *RangeError* exception.

I.e. "growing to the same size" should be a no-op instead of throwing.

**Comment by syg** [comment]
Good call. I think GSAB#resize should be an explicit nop when the resize size is the same, to avoid gratuitous synchronization on updating the length.
