### ISSUE TITLE
Allow resize(0)

### ISSUE THREAD

**Issue by Jamesernator** [tc39/proposal-resizablearraybuffer#22]
The explainer currently says that [a length of zero always denotes a detached buffer](https://github.com/tc39/proposal-resizablearraybuffer#should-resize0-be-allowed), however this isn't true.

`const buffer = new ArrayBuffer(0)` is perfectly acceptable and is not a detached buffer (in particular `buffer.slice()` works, whereas for a detached buffer it throws an error).

The use case of an empty array buffer (including resizable), is simply to indicate there is no data in the buffer. (Compared with detaching, which implies that the buffer is gone and no longer usable).

**Comment by syg** [comment]
Oh, interesting, thanks for the data point.
